version: '3'
services:
  build-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "5001:80"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEBUG=${DEBUG}
    image: edutainment-app:dev 
  production-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "80:80"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEBUG=${DEBUG}
    image: edutainment-app:run